# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-fairhub-pipeline-270fb01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fairhub.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_47f8a67fb85e4a72bd5ea728af1deea6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_306b892e732d45b3b8593d7b51191b75 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fairhub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_47f8a67fb85e4a72bd5ea728af1deea6 }}/fairhub-pipeline:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-fairhub-pipeline-270fb01'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f80f356dbca4660ae9e10615d19f53c }}
        images: 'fairhub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_47f8a67fb85e4a72bd5ea728af1deea6 }}/fairhub-pipeline:${{ github.sha }}'